language: php
php:
  - 7.1
  - 5.6
service:
  - mysql
before_script:
  - composer install --prefer-dist
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS luffy;'
  - php artisan migrate
  - sed -i 's/luffy/information_schema/g' .env
script:  ./vendor/phpunit/phpunit/phpunit -c phpunit.xml